server:
  port: 8080
spring:
  jpa:
    hibernate:
       ddl-auto: create
  application:
    name: E-commerceStore
  datasource:
     url: jdbc:mysql://localhost:3306/Ecommercestore
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: Guler
     password: G8m01sc5

